FROM me/debian-base:latest
RUN set -uex;\
 apt-get update -qy;\
 apt-get -y install lsb-release ca-certificates curl;\
 curl -sSLo /tmp/debsuryorg-archive-keyring.deb https://packages.sury.org/debsuryorg-archive-keyring.deb;\
 dpkg -i /tmp/debsuryorg-archive-keyring.deb;\
 echo "deb [signed-by=/usr/share/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/sury-php.list;\
 apt-get update -qy;\
 apt-get install php7.4 -qy

