# no `copy --from $variable` workaround
ARG IMAGE_REPO
FROM ${IMAGE_REPO}/debian-node:build as build

# distroless
FROM gcr.io/distroless/cc-debian12:latest
COPY --from=build "/build/node" /usr/local

RUN [ "/usr/local/bin/node", "--eval", "console.log(process.version); process.exit()" ]
#ENTRYPOINT [ "/usr/local/bin/node" ]
