# vscode
ARG IMAGE_REPO
ARG VSCODE_COMMIT
# output
ARG EXTEND_IMAGE_REPO_TAG

FROM ${IMAGE_REPO}/vscode-reh:${VSCODE_COMMIT} as vscode

FROM ${EXTEND_IMAGE_REPO_TAG}
ARG UID=500
COPY --from=vscode /usr/local/vscode-server /usr/local/vscode-server
RUN set -uex;\
    mkdir -p /user;\
    chown -R "$UID" /user;
