ARG IMAGE_REPO
ARG VSCODIUM_VERSION
ARG EXTEND_IMAGE_REPO_TAG

FROM ${IMAGE_REPO}/vscodium-reh:${VSCODIUM_VERSION} as vscodium

FROM ${EXTEND_IMAGE_REPO_TAG}
ARG UID=500
COPY --from=vscodium /usr/local/vscodium-server /usr/local/vscodium-server
RUN set -uex;\
    mkdir -p /user;\
    chown -R "$UID" /user;
